---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: host
  gather_facts: False
  vars:
    tenant: ICE_CR
  
  
  

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        host: "{{ aci_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
