---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: localhost
  gather_facts: False

  vars: 
    host: "131.226.217.153"
    username: "admin"
    password: "!v3G@!4@Y"
    tenant: "awx-test2"
 
  
  
  

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
