---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: localhost
  gather_facts: False
 
  
  
  

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
